### ISSUE TITLE
Multiplatform ksp sample with kotlin 1.6.20 - common code generation

### ISSUE THREAD

**Issue by frcouceiro** [evant/kotlin-inject-samples#5]
I was following [your sample](https://github.com/evant/kotlin-inject-samples/blob/main/multiplatform/echo/build.gradle.kts#L41) multiplaform project with Ksp, but given that newer ksp versions no longer have `kspKotlinMetadata`, is there any alternative we can use for pure common code injection ? Thanks in advance!

**Comment by evant** [comment]
Yeah was worried about that when I saw https://github.com/google/ksp/issues/567#issuecomment-1094089187

**Comment by idrisadetunmbi** [comment]
Wondering if there is anything on this yet. Posted this same issue here: https://github.com/evant/kotlin-inject/issues/236. Thanks.

**Comment by tfcporciuncula** [comment]
Just realized we can probably close this issue for the same reason we closed the other https://github.com/evant/kotlin-inject/issues/236
